In [2]:

import os 
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
plays = pd.read_csv('plays.csv')
players = pd.read_csv('players.csv')
playerplay = pd.read_csv('player_play.csv')
df = pd.read_csv('tracking_week_1.csv')

In [4]:
cols = ['gameId','playId', 'possessionTeam','defensiveTeam','quarter', 'down', 'yardsToGo', 'offenseFormation', 'receiverAlignment','passResult','playAction', 'timeToThrow','pff_passCoverage','pff_manZone']

In [5]:
filteredplays = plays.loc[plays['passResult'].notna(), cols]

In [6]:
filteredplays[(filteredplays.gameId == 2022090800) & (filteredplays.playId == 56)]

,gameId,playId,possessionTeam,defensiveTeam,quarter,down,yardsToGo,offenseFormation,receiverAlignment,passResult,playAction,timeToThrow,pff_passCoverage,pff_manZone
13368,2022090800,56,BUF,LA,1,1,10,SHOTGUN,2x2,C,False,2.169,Cover 6-Left,Zone

In [7]:
filteredplays

,gameId,playId,possessionTeam,defensiveTeam,quarter,down,yardsToGo,offenseFormation,receiverAlignment,passResult,playAction,timeToThrow,pff_passCoverage,pff_manZone
0,2022102302,2655,CIN,ATL,3,1,10,EMPTY,3x2,C,False,2.990,Cover-3,Zone
1,2022091809,3698,CIN,DAL,4,1,10,EMPTY,3x2,C,False,1.836,Quarters,Zone
2,2022103004,3146,HOU,TEN,4,3,12,SHOTGUN,2x2,C,False,2.236,Quarters,Zone
3,2022110610,348,KC,TEN,1,2,10,SHOTGUN,2x2,C,False,2.202,Quarters,Zone
8,2022091104,3662,PHI,DET,4,3,12,SHOTGUN,3x1,I,False,1.568,Cover-0,Man
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16117,2022100901,2213,PIT,BUF,3,1,10,I_FORM,2x1,C,True,3.838,Quarters,Zone
16119,2022110604,1051,JAX,LV,2,3,4,SHOTGUN,2x2,I,False,1.860,Cover-2,Zone
16120,2022103005,3492,MIN,ARI,4,1,10,SHOTGUN,2x2,I,False,3.136,Cover-3,Zone
16121,2022092502,2337,KC,IND,3,1,10,SHOTGUN,2x2,R,False,NaN,Quarters,Zone
16122,2022091809,719,DAL,CIN,1,1,10,SINGLEBACK,2x2,I,True,3.070,Cover-3,Zone

In [8]:
cols2 = ['gameId', 'playId', 'nflId','teamAbbr','inMotionAtBallSnap', 'motionSinceLineset', 'routeRan', 'hadPassReception', 'receivingYards']

In [9]:
filteredplayerplay = playerplay[cols2][playerplay['routeRan'].notna()]

In [10]:
filteredplayerplay

,gameId,playId,nflId,teamAbbr,inMotionAtBallSnap,motionSinceLineset,routeRan,hadPassReception,receivingYards
2,2022090800,56,42489,BUF,False,True,IN,1,6
4,2022090800,56,44985,BUF,False,False,OUT,0,0
7,2022090800,56,47879,BUF,False,False,IN,0,0
9,2022090800,56,52536,BUF,False,False,GO,0,0
68,2022090800,122,42489,BUF,False,False,GO,0,0
...,...,...,...,...,...,...,...,...,...
354522,2022110700,3480,44879,NO,False,False,FLAT,0,0
354523,2022110700,3480,46160,NO,False,False,IN,0,0
354526,2022110700,3480,52942,NO,False,False,OUT,1,41
354527,2022110700,3480,53098,NO,False,False,IN,0,0
354528,2022110700,3480,54476,NO,False,False,GO,0,0

In [11]:
merged_playerplay = pd.merge(
    filteredplays[['gameId','playId','possessionTeam','defensiveTeam','quarter','down','yardsToGo','offenseFormation','receiverAlignment','passResult','playAction','timeToThrow','pff_passCoverage','pff_manZone']],
    filteredplayerplay[['gameId','playId','nflId','inMotionAtBallSnap','motionSinceLineset','routeRan','hadPassReception','receivingYards']],
    how='right',
    left_on=['gameId', 'playId'],
    right_on=['gameId', 'playId']
)

In [12]:
merged_playerplay

,gameId,playId,possessionTeam,defensiveTeam,quarter,down,yardsToGo,offenseFormation,receiverAlignment,passResult,playAction,timeToThrow,pff_passCoverage,pff_manZone,nflId,inMotionAtBallSnap,motionSinceLineset,routeRan,hadPassReception,receivingYards
0,2022090800,56,BUF,LA,1,1,10,SHOTGUN,2x2,C,False,2.169,Cover 6-Left,Zone,42489,False,True,IN,1,6
1,2022090800,56,BUF,LA,1,1,10,SHOTGUN,2x2,C,False,2.169,Cover 6-Left,Zone,44985,False,False,OUT,0,0
2,2022090800,56,BUF,LA,1,1,10,SHOTGUN,2x2,C,False,2.169,Cover 6-Left,Zone,47879,False,False,IN,0,0
3,2022090800,56,BUF,LA,1,1,10,SHOTGUN,2x2,C,False,2.169,Cover 6-Left,Zone,52536,False,False,GO,0,0
4,2022090800,122,BUF,LA,1,2,3,SHOTGUN,2x1,C,False,2.903,Cover-3,Zone,42489,False,False,GO,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42774,2022110700,3480,NO,BAL,4,2,10,SHOTGUN,2x2,C,False,2.390,Cover-3,Zone,44879,False,False,FLAT,0,0
42775,2022110700,3480,NO,BAL,4,2,10,SHOTGUN,2x2,C,False,2.390,Cover-3,Zone,46160,False,False,IN,0,0
42776,2022110700,3480,NO,BAL,4,2,10,SHOTGUN,2x2,C,False,2.390,Cover-3,Zone,52942,False,False,OUT,1,41
42777,2022110700,3480,NO,BAL,4,2,10,SHOTGUN,2x2,C,False,2.390,Cover-3,Zone,53098,False,False,IN,0,0
42778,2022110700,3480,NO,BAL,4,2,10,SHOTGUN,2x2,C,False,2.390,Cover-3,Zone,54476,False,False,GO,0,0

In [13]:
tracking_data = pd.read_csv('tracking_week_1.csv')

In [14]:
tracking = tracking_data[tracking_data['frameType'] == 'AFTER_SNAP']

In [15]:
route_runners = playerplay[playerplay['routeRan'].notna()][['gameId', 'playId', 'nflId', 'routeRan']]
defenders = playerplay[playerplay['pff_primaryDefensiveCoverageMatchupNflId'].notna()][['gameId', 'playId', 'nflId', 'pff_primaryDefensiveCoverageMatchupNflId']]
defenders = defenders.rename(columns={'pff_primaryDefensiveCoverageMatchupNflId': 'routeRunnerId'})

In [16]:
merged_df = defenders.merge(route_runners, left_on=['gameId', 'playId', 'routeRunnerId'], right_on=['gameId', 'playId', 'nflId'])

In [17]:
defenders = merged_df[['gameId','playId','nflId_x','routeRunnerId']]

In [18]:
route = pd.merge(
    tracking[['gameId', 'playId', 'nflId', 'frameId', 'time', 'x', 'y']],  # Columns to keep from tracking_df
    route_runners[['gameId', 'playId', 'nflId']],  # Only keep necessary columns from route_runners_df
    on=['gameId', 'playId', 'nflId'],  # Merge on these columns
    how='inner'  # Use an inner join to keep only matching nflIds
)

In [19]:
defend = pd.merge(
    tracking[['gameId', 'playId', 'nflId', 'frameId','time', 'x', 'y']],  # Columns to keep from tracking_df
    defenders[['gameId', 'playId', 'nflId_x', 'routeRunnerId']],  # Necessary columns from defenders_df
    left_on=['gameId', 'playId', 'nflId'],  # Merge on these columns
    right_on=['gameId', 'playId', 'nflId_x'],  # Use nflId_x for the defenders DataFrame
    how='inner'  # Use an inner join to keep only matching nflIds
)

In [20]:
merged_df = pd.merge(
    route,  # Use the entire route_df
    defend[['gameId','playId','nflId','frameId','x','y','routeRunnerId']],  # Use the entire defend_df
    how='inner',  # Use an inner join to keep only matching rows
    left_on=['gameId', 'playId', 'nflId', 'frameId'],  # Merge on these columns in route_df
    right_on=['gameId', 'playId', 'routeRunnerId', 'frameId']  # Match nflId in route_df with routeRunnerId in defend_df
)

In [21]:
merged_df['time_since_snap'] = 0.1

In [22]:
def calculate_time_since_snap(df):
    time = 0.1  # Default time
    lasttime = 0.1
    
    # Initialize last identifiers
    lastgame = None
    lastplay = None
    lastplayer = None
    lastframe = None
    
    # Iterate through each row in the DataFrame
    for i in range(len(df)):
        current_row = df.iloc[i]
        
        # Check if we're still in the same game, play, and player
        if (current_row['gameId'] == lastgame and
                current_row['playId'] == lastplay and
                current_row['nflId_x'] == lastplayer):
            if current_row['frameId'] == lastframe:
                df.at[i, 'time_since_snap'] = lasttime
            elif current_row['frameId'] == lastframe + 1:
                lasttime += 0.1
                df.at[i, 'time_since_snap'] = lasttime
            else:
                # Reset time since snap if frameId is not consecutive
                lasttime = 0.1
                df.at[i, 'time_since_snap'] = lasttime
        else:
            # If gameId, playId, or nflId_x changes, reset
            df.at[i, 'time_since_snap'] = time
            lasttime = time  # Reset lasttime to default

        # Update last identifiers
        lastgame = current_row['gameId']
        lastplay = current_row['playId']
        lastplayer = current_row['nflId_x']
        lastframe = current_row['frameId']

    return df

In [23]:
merged_df = calculate_time_since_snap(merged_df)

In [24]:
merged_df

,gameId,playId,nflId_x,frameId,time,x_x,y_x,nflId_y,x_y,y_y,routeRunnerId,time_since_snap
0,2022091200,85,40026.0,118,2022-09-13 00:16:52.2,39.24,34.29,35459.0,54.43,34.34,40026.0,0.1
1,2022091200,85,40026.0,118,2022-09-13 00:16:52.2,39.24,34.29,42929.0,44.44,30.18,40026.0,0.1
2,2022091200,85,40026.0,119,2022-09-13 00:16:52.3,39.32,34.27,35459.0,54.52,34.35,40026.0,0.2
3,2022091200,85,40026.0,119,2022-09-13 00:16:52.3,39.32,34.27,42929.0,44.45,30.22,40026.0,0.2
4,2022091200,85,40026.0,120,2022-09-13 00:16:52.4,39.45,34.25,35459.0,54.62,34.35,40026.0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...
278883,2022090800,3696,53678.0,171,2022-09-09 03:07:37.7,3.01,50.29,54488.0,7.11,49.36,53678.0,4.9
278884,2022090800,3696,53678.0,172,2022-09-09 03:07:37.8,2.71,50.21,54488.0,7.03,49.24,53678.0,5.0
278885,2022090800,3696,53678.0,173,2022-09-09 03:07:37.9,2.43,50.12,54488.0,6.96,49.12,53678.0,5.1
278886,2022090800,3696,53678.0,174,2022-09-09 03:07:38,2.17,50.02,54488.0,6.89,49.00,53678.0,5.2
278887,2022090800,3696,53678.0,175,2022-09-09 03:07:38.1,1.95,49.91,54488.0,6.83,48.88,53678.0,5.3

In [25]:
merge = pd.merge(
    merged_df,
    plays[['gameId', 'playId', 'timeToThrow']],
    how='left',
    left_on=['gameId', 'playId'],  
    right_on=['gameId', 'playId']  
)

In [84]:
merge = merge[(merge['time_since_snap'] <= merge['timeToThrow']) & (merge['time_since_snap'] >= 1)]

In [85]:
final = merge[['gameId', 'playId', 'frameId', 'nflId_x', 'nflId_y', 'x_x', 'y_x', 'x_y', 'y_y', 'time_since_snap', 'timeToThrow']]

In [86]:
final.rename(columns={
    'nflId_x': 'nflId_runner',
    'nflId_y': 'nflId_defender',
    'x_x': 'x_runner', 
    'y_x': 'y_runner', 
    'x_y': 'x_defender',
    'y_y': 'y_defender'
}, inplace=True)

C:\Users\bhaga\AppData\Local\Temp\ipykernel_40644\911467374.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final.rename(columns={

In [87]:
final['separation'] = ((final['x_runner'] - final['x_defender'])**2 + (final['y_runner'] - final['y_defender'])**2)**0.5

C:\Users\bhaga\AppData\Local\Temp\ipykernel_40644\3475080978.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['separation'] = ((final['x_runner'] - final['x_defender'])**2 + (final['y_runner'] - final['y_defender'])**2)**0.5

In [88]:
final

,gameId,playId,frameId,nflId_runner,nflId_defender,x_runner,y_runner,x_defender,y_defender,time_since_snap,timeToThrow,separation
20,2022091200,85,128,40026.0,35459.0,42.41,33.71,56.00,34.50,1.1,2.069,13.612942
21,2022091200,85,128,40026.0,42929.0,42.41,33.71,45.11,31.30,1.1,2.069,3.619130
22,2022091200,85,129,40026.0,35459.0,43.00,33.65,56.28,34.55,1.2,2.069,13.310462
23,2022091200,85,129,40026.0,42929.0,43.00,33.65,45.23,31.47,1.2,2.069,3.118541
24,2022091200,85,130,40026.0,35459.0,43.62,33.60,56.57,34.61,1.3,2.069,12.989326
...,...,...,...,...,...,...,...,...,...,...,...,...
278855,2022090800,3696,143,53678.0,54488.0,20.23,46.00,16.82,46.89,2.1,2.569,3.524230
278856,2022090800,3696,144,53678.0,54488.0,19.56,46.32,16.40,47.09,2.2,2.569,3.252461
278857,2022090800,3696,145,53678.0,54488.0,18.88,46.63,15.98,47.28,2.3,2.569,2.971952
278858,2022090800,3696,146,53678.0,54488.0,18.19,46.95,15.54,47.49,2.4,2.569,2.704459
278859,2022090800,3696,147,53678.0,54488.0,17.51,47.29,15.10,47.69,2.5,2.569,2.442970

In [89]:
final = final.loc[final.groupby(['gameId', 'playId', 'frameId', 'nflId_runner'])['separation'].idxmin()]

In [90]:
final

,gameId,playId,frameId,nflId_runner,nflId_defender,x_runner,y_runner,x_defender,y_defender,time_since_snap,timeToThrow,separation
262240,2022090800,56,157,42489.0,43294.0,83.83,43.53,77.45,43.82,1.1,2.169,6.386588
262286,2022090800,56,157,44985.0,47844.0,84.67,18.65,82.10,22.20,1.1,2.169,4.382625
262343,2022090800,56,157,47879.0,53532.0,84.03,34.53,79.61,32.75,1.1,2.169,4.764955
262241,2022090800,56,158,42489.0,43294.0,83.40,43.45,77.42,43.83,1.2,2.169,5.992061
262287,2022090800,56,158,44985.0,47844.0,84.20,18.77,81.85,22.10,1.2,2.169,4.075709
...,...,...,...,...,...,...,...,...,...,...,...,...
18261,2022091200,3826,117,52454.0,47941.0,53.77,41.65,52.99,44.36,2.7,2.836,2.820018
18346,2022091200,3826,117,53464.0,42827.0,70.68,16.58,57.86,18.40,2.7,2.836,12.948544
18177,2022091200,3826,118,46109.0,54618.0,55.99,15.63,56.20,15.01,2.8,2.836,0.654599
18262,2022091200,3826,118,52454.0,47941.0,52.95,41.84,52.68,44.43,2.8,2.836,2.604035
18347,2022091200,3826,118,53464.0,42827.0,70.68,16.09,57.89,17.81,2.8,2.836,12.905135

In [91]:
max_separation_per_play = final.groupby(['gameId', 'playId', 'nflId_runner'])['separation'].max().reset_index()
max_separation_per_play.columns = ['gameId', 'playId', 'routeRunnerId', 'maxSeparation']

In [92]:
result = pd.merge(
    max_separation_per_play,
    final[['gameId', 'playId', 'nflId_runner', 'nflId_defender', 'separation', 'time_since_snap', 'timeToThrow']],  # Select necessary columns
    how='left',
    left_on=['gameId', 'playId', 'routeRunnerId', 'maxSeparation'],  # Join on the maximum separation
    right_on=['gameId', 'playId', 'nflId_runner', 'separation']  # Join on the separation value
)

In [93]:
result = result.drop(columns=['nflId_runner'])
result

,gameId,playId,routeRunnerId,maxSeparation,nflId_defender,separation,time_since_snap,timeToThrow
0,2022090800,56,42489.0,6.386588,43294.0,6.386588,1.1,2.169
1,2022090800,56,44985.0,4.382625,47844.0,4.382625,1.1,2.169
2,2022090800,56,47879.0,4.764955,53532.0,4.764955,1.1,2.169
3,2022090800,122,42489.0,7.504166,42816.0,7.504166,1.1,2.903
4,2022090800,122,44985.0,5.287343,43294.0,5.287343,1.1,2.903
...,...,...,...,...,...,...,...,...
4151,2022091200,3795,52454.0,7.688654,47941.0,7.688654,1.1,1.983
4152,2022091200,3795,52526.0,5.955476,44873.0,5.955476,1.1,1.983
4153,2022091200,3826,46109.0,1.381774,54618.0,1.381774,1.1,2.836
4154,2022091200,3826,52454.0,8.478095,47941.0,8.478095,1.1,2.836
4155,2022091200,3826,53464.0,12.948544,42827.0,12.948544,2.7,2.836

In [94]:
merged_playerplay.columns

Index(['gameId', 'playId', 'possessionTeam', 'defensiveTeam', 'quarter',
       'down', 'yardsToGo', 'offenseFormation', 'receiverAlignment',
       'passResult', 'playAction', 'timeToThrow', 'pff_passCoverage',
       'pff_manZone', 'nflId', 'inMotionAtBallSnap', 'motionSinceLineset',
       'routeRan', 'hadPassReception', 'receivingYards'],
      dtype='object')

In [95]:
week1 = pd.merge(
    merged_playerplay,
    result,
    how = 'right',
    left_on=['gameId','playId','nflId'],
    right_on=['gameId','playId','routeRunnerId']
)

In [96]:
week1.columns

Index(['gameId', 'playId', 'possessionTeam', 'defensiveTeam', 'quarter',
       'down', 'yardsToGo', 'offenseFormation', 'receiverAlignment',
       'passResult', 'playAction', 'timeToThrow_x', 'pff_passCoverage',
       'pff_manZone', 'nflId', 'inMotionAtBallSnap', 'motionSinceLineset',
       'routeRan', 'hadPassReception', 'receivingYards', 'routeRunnerId',
       'maxSeparation', 'nflId_defender', 'separation', 'time_since_snap',
       'timeToThrow_y'],
      dtype='object')

In [103]:
new_column_order = [
    'gameId', 
    'playId', 
    'routeRunnerId',  # Move routeRunnerId to 3rd
    'nflId_defender',  # Move nflId_defender to 4th
    'possessionTeam', 
    'defensiveTeam', 
    'quarter', 
    'down', 
    'yardsToGo', 
    'offenseFormation', 
    'receiverAlignment', 
    'passResult', 
    'playAction', 
    'timeToThrow_x', 
    'pff_passCoverage', 
    'pff_manZone', 
    'inMotionAtBallSnap', 
    'motionSinceLineset', 
    'routeRan', 
    'hadPassReception', 
    'receivingYards',
    'time_since_snap',
    'maxSeparation'
]

In [98]:
week1 = week1.drop(columns='nflId')

In [104]:
week1 = week1[new_column_order]
week1.columns

Index(['gameId', 'playId', 'routeRunnerId', 'nflId_defender', 'possessionTeam',
       'defensiveTeam', 'quarter', 'down', 'yardsToGo', 'offenseFormation',
       'receiverAlignment', 'passResult', 'playAction', 'timeToThrow_x',
       'pff_passCoverage', 'pff_manZone', 'inMotionAtBallSnap',
       'motionSinceLineset', 'routeRan', 'hadPassReception', 'receivingYards',
       'time_since_snap', 'maxSeparation'],
      dtype='object')

In [105]:
week1

,gameId,playId,routeRunnerId,nflId_defender,possessionTeam,defensiveTeam,quarter,down,yardsToGo,offenseFormation,...,timeToThrow_x,pff_passCoverage,pff_manZone,inMotionAtBallSnap,motionSinceLineset,routeRan,hadPassReception,receivingYards,time_since_snap,maxSeparation
0,2022090800,56,42489.0,43294.0,BUF,LA,1,1,10,SHOTGUN,...,2.169,Cover 6-Left,Zone,False,True,IN,1,6,1.1,6.386588
1,2022090800,56,44985.0,47844.0,BUF,LA,1,1,10,SHOTGUN,...,2.169,Cover 6-Left,Zone,False,False,OUT,0,0,1.1,4.382625
2,2022090800,56,47879.0,53532.0,BUF,LA,1,1,10,SHOTGUN,...,2.169,Cover 6-Left,Zone,False,False,IN,0,0,1.1,4.764955
3,2022090800,122,42489.0,42816.0,BUF,LA,1,2,3,SHOTGUN,...,2.903,Cover-3,Zone,False,False,GO,0,0,1.1,7.504166
4,2022090800,122,44985.0,43294.0,BUF,LA,1,2,3,SHOTGUN,...,2.903,Cover-3,Zone,False,False,POST,0,0,1.1,5.287343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4151,2022091200,3795,52454.0,47941.0,DEN,SEA,4,2,14,SHOTGUN,...,1.983,Cover-3,Zone,False,False,HITCH,0,0,1.1,7.688654
4152,2022091200,3795,52526.0,44873.0,DEN,SEA,4,2,14,SHOTGUN,...,1.983,Cover-3,Zone,False,False,SLANT,0,0,1.1,5.955476
4153,2022091200,3826,46109.0,54618.0,DEN,SEA,4,3,14,SHOTGUN,...,2.836,Cover 6-Left,Zone,False,False,GO,0,0,1.1,1.381774
4154,2022091200,3826,52454.0,47941.0,DEN,SEA,4,3,14,SHOTGUN,...,2.836,Cover 6-Left,Zone,False,False,GO,0,0,1.1,8.478095
4155,2022091200,3826,53464.0,42827.0,DEN,SEA,4,3,14,SHOTGUN,...,2.836,Cover 6-Left,Zone,False,False,FLAT,1,9,2.7,12.948544

In [109]:
week1.loc[week1['maxSeparation'] > 20, ['time_since_snap', 'timeToThrow_x', 'pff_manZone','hadPassReception', 'receivingYards', 'maxSeparation']]

,time_since_snap,timeToThrow_x,pff_manZone,hadPassReception,receivingYards,maxSeparation
355,1.1,3.403,Zone,0,0,22.696795
717,7.9,7.920,Zone,1,51,24.001594
728,5.3,5.338,Man,0,0,28.998464
771,1.1,2.770,Zone,0,0,22.403397
857,5.1,5.165,Zone,0,0,22.530142
925,1.1,2.836,Zone,0,0,21.107139
1256,2.6,2.679,Zone,0,0,21.061208
1260,2.2,2.269,Zone,0,0,24.907690
1337,3.4,3.431,Zone,0,0,23.536179
1518,1.1,3.031,Zone,0,0,22.569293
1558,3.5,3.550,Zone,1,4,20.718844
1822,2.0,3.471,Zone,0,0,20.380886
1936,1.1,2.837,Zone,0,0,20.384968
1940,1.1,2.969,Zone,1,5,21.705163
2103,1.1,2.837,Zone,0,0,20.059177
2584,3.1,3.170,Zone,1,4,34.771603
2587,3.1,3.170,Zone,0,0,40.524151
2835,3.8,3.971,Zone,1,25,21.245856
2951,5.0,5.005,Zone,0,0,25.876911
3513,1.1,3.803,Zone,1,36,23.289161
3607,1.1,5.339,Zone,0,0,23.011358
3642,1.1,1.969,Zone,1,13,23.392772
3672,3.8,4.498,Zone,0,0,22.684276
3715,3.0,3.904,Zone,0,0,21.939674
3931,3.8,6.774,Zone,0,0,23.891609
3933,1.1,3.126,Zone,0,0,20.193794
3991,3.5,3.571,Zone,0,0,30.633454

In [107]:
week1[week1['hadPassReception']==1]

,gameId,playId,routeRunnerId,nflId_defender,possessionTeam,defensiveTeam,quarter,down,yardsToGo,offenseFormation,...,timeToThrow_x,pff_passCoverage,pff_manZone,inMotionAtBallSnap,motionSinceLineset,routeRan,hadPassReception,receivingYards,time_since_snap,maxSeparation
0,2022090800,56,42489.0,43294.0,BUF,LA,1,1,10,SHOTGUN,...,2.169,Cover 6-Left,Zone,False,True,IN,1,6,1.1,6.386588
5,2022090800,122,47857.0,38577.0,BUF,LA,1,2,3,SHOTGUN,...,2.903,Cover-3,Zone,False,False,FLAT,1,6,2.3,11.756330
7,2022090800,167,42489.0,43298.0,BUF,LA,1,2,8,EMPTY,...,1.868,Cover-3,Zone,False,False,SLANT,1,12,1.1,2.651886
13,2022090800,212,52494.0,38577.0,BUF,LA,1,2,9,SHOTGUN,...,4.905,Cover-1,Man,False,False,ANGLE,1,8,1.1,8.402869
15,2022090800,236,52536.0,43294.0,BUF,LA,1,3,1,I_FORM,...,2.636,Cover-3,Zone,True,True,CORNER,1,26,2.6,7.888346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4130,2022091200,3491,47803.0,53534.0,SEA,DEN,4,2,8,SHOTGUN,...,2.478,Quarters,Zone,False,False,SCREEN,1,2,2.4,3.800118
4139,2022091200,3596,52526.0,42543.0,DEN,SEA,4,3,5,SHOTGUN,...,3.029,Cover-3,Zone,False,False,HITCH,1,5,1.1,10.800463
4144,2022091200,3628,52526.0,44873.0,DEN,SEA,4,1,10,SHOTGUN,...,1.902,Cover-3 Seam,Zone,False,False,HITCH,1,6,1.1,9.984813
4148,2022091200,3723,53464.0,52435.0,DEN,SEA,4,3,2,SHOTGUN,...,2.717,Cover-3 Seam,Zone,False,False,OUT,1,9,1.9,7.553125
4155,2022091200,3826,53464.0,42827.0,DEN,SEA,4,3,14,SHOTGUN,...,2.836,Cover 6-Left,Zone,False,False,FLAT,1,9,2.7,12.948544